// TODO: Add proper type for row data
const rows = [
  {
    id: 1,
    date: "Jun 30, 2025",
    description: "Netflix Subscription",
    amount: "$15.49",
    category: "Subscriptions",
  },
  {
    id: 2,
    date: "Jun 29, 2025",
    description: "Uber Eats - Late Night Snack",
    amount: "$17.50",
    category: "Food & Drink",
  },
  {
    id: 3,
    date: "Jun 28, 2025",
    description: "Amazon - Tech Accessory",
    amount: "$12.99",
    category: "Shopping",
  },
  {
    id: 4,
    date: "Jun 27, 2025",
    description: "Spotify Premium",
    amount: "$10.99",
    category: "Subscriptions",
  },
  {
    id: 5,
    date: "Jun 26, 2025",
    description: "Shell Gas Station",
    amount: "$42.85",
    category: "Transport",
  },
  {
    id: 6,
    date: "Jun 25, 2025",
    description: "CVS Pharmacy - Essentials",
    amount: "$23.17",
    category: "Health & Fitness",
  },
  {
    id: 7,
    date: "Jun 24, 2025",
    description: "Starbucks - Iced Coffee",
    amount: "$4.65",
    category: "Food & Drink",
  },
  {
    id: 8,
    date: "Jun 23, 2025",
    description: "Trader Joe's Grocery",
    amount: "$56.22",
    category: "Groceries",
  },
  {
    id: 9,
    date: "Jun 22, 2025",
    description: "YouTube Premium",
    amount: "$13.99",
    category: "Subscriptions",
  },
  {
    id: 10,
    date: "Jun 21, 2025",
    description: "Apple - iCloud Storage",
    amount: "$0.99",
    category: "Subscriptions",
  },
  {
    id: 11,
    date: "Jun 20, 2025",
    description: "Lyft Ride to Work",
    amount: "$18.30",
    category: "Transport",
  },
  {
    id: 12,
    date: "Jun 19, 2025",
    description: "Chipotle - Lunch Bowl",
    amount: "$11.40",
    category: "Food & Drink",
  },
  {
    id: 13,
    date: "Jun 18, 2025",
    description: "Planet Fitness - Monthly Fee",
    amount: "$10.00",
    category: "Health & Fitness",
  },
  {
    id: 14,
    date: "Jun 17, 2025",
    description: "New York Times Subscription",
    amount: "$4.00",
    category: "Subscriptions",
  },
  {
    id: 15,
    date: "Jun 16, 2025",
    description: "Subway - Breakfast Sandwich",
    amount: "$6.75",
    category: "Food & Drink",
  },
  {
    id: 16,
    date: "Jun 15, 2025",
    description: "Amazon Prime Monthly",
    amount: "$14.99",
    category: "Subscriptions",
  },
  {
    id: 17,
    date: "Jun 14, 2025",
    description: "Best Buy - Portable Charger",
    amount: "$24.95",
    category: "Shopping",
  },
  {
    id: 18,
    date: "Jun 13, 2025",
    description: "Walgreens - Skincare Products",
    amount: "$19.60",
    category: "Health & Fitness",
  },
  {
    id: 19,
    date: "Jun 12, 2025",
    description: "Domino's Pizza - Dinner",
    amount: "$22.35",
    category: "Food & Drink",
  },
  {
    id: 20,
    date: "Jun 11, 2025",
    description: "LIRR Monthly Pass",
    amount: "$261.00",
    category: "Transit",
  },
];

export default rows;
